cic:
  enabled: true
  nsPort: 443
  nsProtocol: HTTPS
  nsIP: X.X.X.X
  adcCredentialSecret: nslogin
  entityPrefix: netflix
  image: 'quay.io/citrix/citrix-k8s-ingress-controller:1.13.20'
  license:
    accept: 'Yes'
  ingressClass:
    - netflix-vpx
  logLevel: INFO
  coeConfig: 
    required: true
    timeseries:
      port: 5563
      metrics:
        enable: true
        mode: 'avro'
    distributedTracing:
      enable: true
      samplingrate: 100
    transactions:
      enable: true
      port: 5557
    endpoint:
      server: X.X.X.X
  nodeWatch: true
cpx:
  enabled: true
  image: 'quay.io/citrix/citrix-k8s-cpx-ingress:13.0-76.29'
  cic:
    required: true
    image: 'quay.io/citrix/citrix-k8s-ingress-controller:1.13.20'
  license:
    accept: 'Yes'
  entityPrefix: cetflix
  logLevel: INFO
  ADMSettings:
    ADMIP: X.X.X.X
    ADMFingerPrint: XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX.XX 
    loginSecret: admlogin
  coeConfig:
    required: true
    timeseries:
      port: 5563
      metrics:
        enable: true
        mode: 'avro'
    distributedTracing:
      enable: true
      samplingrate: 100
    endpoint:
      server: X.X.X.X
  ingressClass:
    - netflix-cpx
