apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
    name: citrix-egressgateway
    namespace: {{ .Release.Namespace }}
spec:
    maxReplicas: 1
    minReplicas: 1
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: citrix-egressgateway
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 60
---
apiVersion: v1
kind: Service
metadata:
  name: citrix-egressgateway
  namespace: {{ .Release.Namespace }}
  annotations:
  labels:
    app: {{ .Values.egressGateway.label | default "citrix-egressgateway" }}
spec:
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: {{ .Values.egressGateway.label | default "citrix-egressgateway" }}
