apiVersion: v2
name: citrix-ipam-controller
description: A Helm chart for Citrix IPAM Controller which automatically allocate an IP address to the service of type LoadBalancer.
version: 0.0.1
appVersion: "0.0.1"
type: application
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-k8s-ingress-controller
maintainers:
- name: priyankash-citrix
  email: priyanka.sharma@citrix.com
