# Default values for citrix-cpx-with-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Citrix ADC CPX config details
image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-64.35
pullPolicy: IfNotPresent

mgmtHttpPort: 9080
mgmtHttpsPort: 9443
openshift: false
aws: False
nodeSelector:
  key:
  value:

serviceType:
  loadBalancer:
    enabled: False
  nodePort:
    enabled: False
    httpPort:
    httpsPort:

serviceAnnotations:
  awsLB:
    sslCert:
    backendProtocol:
    sslPorts:
    negotiationPolicy:
    proxyProtocol: False
    resourcesTags:

# Citrix Ingress Controller config details
cic:
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.9.20
  pullPolicy: IfNotPresent
  required: true
entityPrefix:
license:
  accept: no
ingressClass:
logLevel: DEBUG
defaultSSLCertSecret:
logProxy:
kubernetesURL:

cicSettings:
  required: False
  cicConfig:
    NS_HTTP2_SERVER_SIDE: "OFF"
    NS_COOKIE_VERSION: "0"

# Citrix ADM/License Server config details
ADMSettings:
  licenseServerIP:
  licenseServerPort: 27000
  ADMIP:
  ADMFingerPrint:
  loginSecret:
  bandWidthLicense: false
  bandWidth:
  vCPULicense: false
  cpxCores:

# Exporter config details
exporter:
  required: false
  image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.6
  pullPolicy: IfNotPresent
  ports:
    containerPort: 8888


# For CRDs supported by Citrix Ingress Controller
crds:
  install: false
  retainOnDelete: false

# Config required to be done by Citrix Ingress Controller for sending metrics to Citrix Observability Exporter
coeConfig:
  required: false
  distributedTracing:
    enable: false
    samplingrate: 100
  endpoint:
    server:
  timeseries:
    port: 5563
    metrics:
      enable: false
      mode: 'avro'
    auditlogs:
      enable: false
    events:
      enable: false
  transactions:
    enable: false
    port: 5557

# Specifies whether a ServiceAccount should be created
serviceAccount:
  create: true
  # The name of the ServiceAccount to use.
  # If not set and `create` is true, a name is generated using the fullname template
  # name:
