cic:
  enabled: False
  
  image: quay.io/citrix/citrix-k8s-ingress-controller:1.9.2
  pullPolicy: IfNotPresent
  openshift: false
  loginFileName:
  nsIP: x.x.x.x
  nsVIP:
  license:
    accept: no
  nsPort: 443
  nsProtocol: HTTPS
  logLevel: DEBUG
  nsNamespace:
  kubernetesURL:
  ingressClass:
  defaultSSLCert:
  ipam: False
  logProxy:
  nodeWatch: false
  http2ServerSide: "OFF"
  nodeSelector:
    key:
    value:

  exporter:
    required: false
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.6
    pullPolicy: IfNotPresent
    ports:
      containerPort: 8888

  crds:
    install: true
    retainOnDelete: false

  coeConfig:
    required: false
    distributedTracing:
      enable: false
      samplingrate: 100
    endpoint:
      server:
    timeseries:
      port: 30002
      metrics:
        enable: false
        mode: 'avro'
      auditlogs:
        enable: false
      events:
        enable: false
    transactions:
      enable: false
      port: 30001

gslb:
  enabled: False

  image: quay.io/citrix/citrix-k8s-ingress-controller:1.9.2
  pullPolicy: IfNotPresent
  openshift: false
  localRegion:
  localCluster:
  license:
    accept: no
  nsPort: 443
  nsProtocol: HTTPS
  logLevel: DEBUG
  nsNamespace:
  kubernetesURL:
  sitedata:

  crds:
    install: true
    retainOnDelete: false

cpx:
  enabled: False

  image: quay.io/citrix/citrix-k8s-cpx-ingress:13.0-58.30
  pullPolicy: IfNotPresent
  cic:
    image: quay.io/citrix/citrix-k8s-ingress-controller:1.9.2
    pullPolicy: IfNotPresent
    required: true

  mgmtHttpPort: 9080
  mgmtHttpsPort: 9443
  openshift: false
  nsNamespace:
  license:
    accept: no
  ingressClass:
  logLevel: DEBUG
  defaultSSLCert:
  logProxy:
  http2ServerSide: "OFF"
  nodeSelector:
    key:
    value:

  serviceType:
    loadBalancer:
      enabled: False
    nodePort:
      enabled: False
      httpPort:
      httpsPort:

  cpxServiceAnnotations:
    awsLB:
      sslCert:
      backendProtocol:
      sslPorts:
      negotiationPolicy:
      proxyProtocol: False
      resourcesTags:

  ADMSettings:
    licenseServerIP:
    licenseServerPort: 27000
    ADMIP:
    ADMFingerPrint:
    loginSecret:
    bandWidthLicense: false
    bandWidth:
    vCPULicense: false
    cpxCores:

  exporter:
    required: false
    image: quay.io/citrix/citrix-adc-metrics-exporter:1.4.6
    pullPolicy: IfNotPresent
    ports:
      containerPort: 8888

  coeConfig:
    required: false
    distributedTracing:
      enable: false
      samplingrate: 100
    endpoint:
      server:
    timeseries:
      port: 5563
      metrics:
        enable: false
        mode: 'avro'
      auditlogs:
        enable: false
      events:
        enable: false
    transactions:
      enable: false
      port: 5557

  crds:
    install: true
    retainOnDelete: false

ci-ingress:
  enabled: False

  citrixCPX: false 

  metricExporter:
    required: true
    image: quay.io/citrix/citrix-adc-metrics-exporter
    version: 1.4.0
    port: 8888
    secure: "YES"
    logLevel: ERROR
    imagePullPolicy: IfNotPresent

  istioAdaptor:
    image: quay.io/citrix/citrix-istio-adaptor
    tag: 1.2.0
    imagePullPolicy: IfNotPresent
    netscalerUrl: null 
    proxyType: router
    secureConnect: true
    vserverIP:
    netProfile:
    ADMIP: 
    ADMFingerPrint:
    coeURL:
 
  istioPilot:
    name: istio-pilot
    namespace: istio-system
    secureGrpcPort: 15011
    insecureGrpcPort: 15010
    SAN: spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account

  ingressGateway:
    image: quay.io/citrix/citrix-k8s-cpx-ingress
    tag: 13.0-47.22
    imagePullPolicy: IfNotPresent
    EULA: NO
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    httpNodePort: 30180
    httpsNodePort: 31443
    lightWeightCPX: 1 
    secretVolumes:
    #licenseServerIP: this value will be taken from istioAdaptor.ADMIP
    licenseServerPort: 27000 
    label: citrix-ingressgateway
    tcpPort:

ci-sidecar:
  enabled: False

  istioAdaptor:
    image: quay.io/citrix/citrix-istio-adaptor 
    tag: 1.2.0
    imagePullPolicy: IfNotPresent
    netscalerUrl: "http://127.0.0.1"
    proxyType: sidecar
    secureConnect: true
    ADMIP: 
    ADMFingerPrint: 
    coeURL:
 
  istioPilot:
    name: istio-pilot
    namespace: istio-system
    secureGrpcPort: 15011
    insecureGrpcPort: 15010
    SAN: "spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account"

  cpxProxy:
    image: quay.io/citrix/citrix-k8s-cpx-ingress 
    tag: 13.0-47.22
    imagePullPolicy: IfNotPresent
    EULA: NO
    cpxSidecarMode: YES
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    #licenseServerIP: this value is taken from istio.Adaptor.ADMIP
    licenseServerPort: 27000

  sidecarWebHook:
    webhookImage: gcr.io/istio-release/sidecar_injector
    webhookImageVersion: 1.0.0
    imagePullPolicy: IfNotPresent

  webhook:
    injectionLabelName: cpx-injection

cnc:
  enabled: False
  image: quay.io/citrix/citrix-k8s-node-controller
  tag: 2.0.0
  pullPolicy: IfNotPresent
  license:
    accept: no
  nsIP:
  loginFileName:
  network:
  vtepIP:
  vxlan:
    id:
    port: 

  serviceAccount:
    create: true

coe:
  enabled: False
  image: "quay.io/citrix/citrix-observability-exporter:1.1.001"
  pullPolicy: IfNotPresent
  replicas: 1
  license:
    accept: no 
  transaction:
    nodePort: 30001
  ns_tracing:
    enabled: false
    server: "zipkin:9411/api/v1/spans" 
  elasticsearch:
    enabled: false
    server:
  kafka:
    enabled: false
    broker:
    topic:
  timeseries:
    enabled: false
    nodePort: 30002

ipam:
  enabled: False
  image: quay.io/citrix/citrix-ipam-controller
  tag: 0.0.1
  pullPolicy: IfNotPresent

  vipRange:
