{{- if eq .Values.citrixCPX false }}
apiVersion: v1
kind: Secret
metadata:
    name: nslogin
    namespace: {{ .Release.Namespace }}
type: Opaque
data:
    username: {{ required "Mention username for the Secret" .Values.nslogin.username | b64enc | quote }}
    password: {{ required "Mention password for the Secret" .Values.nslogin.password | b64enc | quote }}
{{- end }}
