apiVersion: v1
appVersion: "1.6.4"
description: A Helm chart to deploy resources which install Citrix ADC CPX in Istio Service Mesh as sidecar in application pod
name: citrix-cpx-istio-sidecar-injector
version: 0.9.5
icon: https://raw.githubusercontent.com/citrix/citrix-helm-charts/gh-pages/icon.png 
home: https://www.citrix.com
sources:
- https://github.com/citrix/citrix-istio-adaptor
maintainers:
- name: dheerajng
  email: dhiraj.gedam@citrix.com
- name: subashd
  email: subash.dangol@citrix.com 
